# Generated by Django 5.2.5 on 2025-10-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Materials',
        ),
    ]
