# Generated by Django 5.2.5 on 2025-10-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='category',
            field=models.CharField(default='product', max_length=50),
        ),
    ]
